### ISSUE TITLE
[Dev Task] TESTING - Create Auto tests for expenses

### ISSUE THREAD

**Issue by student0Zero** [student0Zero/Spinning-Plates-Budgeter#63]
# Description
create test.py for expenses
  
---
## Breakdown of Activities
- [x] Action: create test.py
- [x] Action: run test.py
- [x] Action: All Tests Pass

---
## Test Results: #1
2 tests failed expenses/tests.py (details in comments below)

### Analysis of results:
The test failures indicate that the create_expenses and edit_expenses views are redirecting to the home page ('/') instead of the expected '/expenses/view_expenses/'. This is likely due to the form validation failing because some required fields are missing. (missing description field) 

### Fixing the tests by ensuring all required fields are provided:
- [x] Make sure that all required fields are included in the test data for the create_expenses and edit_expenses views. Add ''Description' field

### Check the Redirect URL:
- [x] Ensure that the views are correctly redirecting to '/expenses/view_expenses/' upon successful form submission.

## Test Results: #2 
2 tests dailed expenses/test.py (details in comments below)

### Analysis of results:
tests are failing because the form returns a negative number for expenses. the tests are looking for a positive value.

**Comment by student0Zero** [comment]
##################
# FAILED TESTS RESULTS
##################

gitpod /workspace/Spinning-Plates-Budgeter (main) $ python manage.py test expenses
Found 8 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.<ul class="errorlist"><li>date<ul class="errorlist"><li>This field is required.</li></ul></li><li>amount<ul class="errorlist"><li>This field is required.</li></ul></li><li>description<ul class="errorlist"><li>This field is required.</li></ul></li><li>category<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
.<ul class="errorlist"><li>description<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
F...<ul class="errorlist"><li>date<ul class="errorlist"><li>This field is required.</li></ul></li><li>amount<ul class="errorlist"><li>This field is required.</li></ul></li><li>description<ul class="errorlist"><li>This field is required.</li></ul></li><li>category<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
.<ul class="errorlist"><li>description<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
F
======================================================================
FAIL: test_create_expense_post_valid (expenses.tests.ExpenseViewTests.test_create_expense_post_valid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Spinning-Plates-Budgeter/expenses/tests.py", line 80, in test_create_expense_post_valid
    self.assertRedirects(response, reverse('view_expenses'))
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/test/testcases.py", line 566, in assertRedirects
    self.assertURLEqual(
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/test/testcases.py", line 591, in assertURLEqual
    self.assertEqual(
AssertionError: '/' != '/expenses/view_expenses'
- /
+ /expenses/view_expenses
 : Response redirected to '/', expected '/expenses/view_expenses'Expected '/' to equal '/expenses/view_expenses'.

======================================================================
FAIL: test_edit_expense_post_valid (expenses.tests.ExpenseViewTests.test_edit_expense_post_valid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Spinning-Plates-Budgeter/expenses/tests.py", line 37, in test_edit_expense_post_valid
    self.assertRedirects(response, reverse('view_expenses'))
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/test/testcases.py", line 566, in assertRedirects
    self.assertURLEqual(
  File "/workspace/.pip-modules/lib/python3.12/site-packages/django/test/testcases.py", line 591, in assertURLEqual
    self.assertEqual(
AssertionError: '/' != '/expenses/view_expenses'
- /
+ /expenses/view_expenses
 : Response redirected to '/', expected '/expenses/view_expenses'Expected '/' to equal '/expenses/view_expenses'.

----------------------------------------------------------------------
Ran 8 tests in 9.600s

FAILED (failures=2)
Destroying test database for alias 'default'...

##################
# PASSED TESTS RESULTS
##################

**Comment by student0Zero** [comment]
# Test Result #2
gitpod /workspace/Spinning-Plates-Budgeter (main) $ python manage.py test expenses
Found 8 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.<ul class="errorlist"><li>date<ul class="errorlist"><li>This field is required.</li></ul></li><li>amount<ul class="errorlist"><li>This field is required.</li></ul></li><li>description<ul class="errorlist"><li>This field is required.</li></ul></li><li>category<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
.F...<ul class="errorlist"><li>date<ul class="errorlist"><li>This field is required.</li></ul></li><li>amount<ul class="errorlist"><li>This field is required.</li></ul></li><li>description<ul class="errorlist"><li>This field is required.</li></ul></li><li>category<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
.F
======================================================================
FAIL: test_create_expense_post_valid (expenses.tests.ExpenseViewTests.test_create_expense_post_valid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Spinning-Plates-Budgeter/expenses/tests.py", line 87, in test_create_expense_post_valid
    self.assertTrue(Expense.objects.filter(category='Party Test Data', description='Freelance Django project', amount=Decimal('200.00'), user=self.user).exists())
AssertionError: False is not true

======================================================================
FAIL: test_edit_expense_post_valid (expenses.tests.ExpenseViewTests.test_edit_expense_post_valid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Spinning-Plates-Budgeter/expenses/tests.py", line 42, in test_edit_expense_post_valid
    self.assertEqual(self.expense.amount, Decimal('150.00'))
AssertionError: Decimal('-150.00') != Decimal('150.00')

----------------------------------------------------------------------
Ran 8 tests in 9.827s

FAILED (failures=2)
Destroying test database for alias 'default'...

# Edited tests re-run results:
All Pass
